### ISSUE TITLE
Move OLM repo to Isovalent Org

### ISSUE THREAD

**Issue by xmulligan** [cilium/cilium-olm#85]
I was looking at the way other CNCF projects publish OLMs. For Antrea, [VMware publishes it](https://github.com/vmware/antrea-operator-for-kubernetes), submariner has [one](https://catalog.redhat.com/software/containers/rhacm2/submariner-addon-rhel8/5fa56fcaf0de7651d429352c) but I'm not it's not in the OSS Github repo, and Kube-OVN currently doesn't have one.

Cilium OLM should live in the Isovalent Github org rather than the Cilium one since it is published by Isovalent.

**Comment by joestringer** [comment]
I think this makes sense. Red Hat has requirements around the `Vendor` so I don't think the Cilium community can register there and publish builds itself directly. Given that this is currently a courtesy provided by Isovalent, I think it is reasonable to move the repo there.

**Comment by xmulligan** [comment]
@nathanjsweet When do you think this could happen?

**Comment by michi-covalent** [comment]
what should we do about the documentation? https://docs.cilium.io/en/v1.13/installation/k8s-install-openshift-okd/ references `cilium/cilium-olm` repository 🤔

**Comment by nathanjsweet** [comment]
We should keep it open source, but it should live in the Isovalent org. We'll fork this to isovalent/cilium-olm, reference the new repository in this one, republish the cilium docs to point to the new repository, then archive this repository. If anyone from the CNCF wants to go to the trouble of resurrecting this repository to start publishing OSS Cilium on Openshift through CNCF-controlled accounts, they'll still be able to do that, and we will happily oblige the change in responsibility.
